import { 
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { Idea } from '../';

@table('ideas')
export class IdeaEntity implements Idea {
    
    @autoGeneratedHashKey()
    id: string;

    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    description: string;
}