import { 
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { StepProject } from '../';

@table('step_projects')
export class StepProjectEntity implements StepProject {
    
    @autoGeneratedHashKey()
    id: string;
    
    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    description: string;
}