import { 
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { Task } from '../';

@table('tasks')
export class TaskEntity implements Task {

    @autoGeneratedHashKey()
    id: string;

    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    description: string;
}